export const LANGUAGE_NAMES: Record<string, string> = {
  en: "English",
  de: "German",
  fr: "French",
  it: "Italian",
  es: "Spanish",
  ro: "Romanian",
  ja: "Japanese",
  ko: "Korean",
  "zh-Hans": "Chinese (Simplified)",
  "zh-Hant": "Chinese (Traditional)",
  pt: "Portuguese",
  "pt-BR": "Portuguese (Brazil)",
  ru: "Russian",
  ar: "Arabic",
  nl: "Dutch",
  pl: "Polish",
  tr: "Turkish",
  sv: "Swedish",
  da: "Danish",
  fi: "Finnish",
  nb: "Norwegian",
  cs: "Czech",
  el: "Greek",
  he: "Hebrew",
  hi: "Hindi",
  hu: "Hungarian",
  id: "Indonesian",
  ms: "Malay",
  sk: "Slovak",
  th: "Thai",
  uk: "Ukrainian",
  vi: "Vietnamese",
};

export const FLAG_EMOJIS: Record<string, string> = {
  en: "🇺🇸",
  de: "🇩🇪",
  fr: "🇫🇷",
  it: "🇮🇹",
  es: "🇪🇸",
  ro: "🇷🇴",
  ja: "🇯🇵",
  ko: "🇰🇷",
  "zh-Hans": "🇨🇳",
  "zh-Hant": "🇹🇼",
  pt: "🇵🇹",
  "pt-BR": "🇧🇷",
  ru: "🇷🇺",
  ar: "🇸🇦",
  nl: "🇳🇱",
  pl: "🇵🇱",
  tr: "🇹🇷",
  sv: "🇸🇪",
  da: "🇩🇰",
  fi: "🇫🇮",
  nb: "🇳🇴",
  cs: "🇨🇿",
  el: "🇬🇷",
  he: "🇮🇱",
  hi: "🇮🇳",
  hu: "🇭🇺",
  id: "🇮🇩",
  ms: "🇲🇾",
  sk: "🇸🇰",
  th: "🇹🇭",
  uk: "🇺🇦",
  vi: "🇻🇳",
};

export const AVAILABLE_LANGUAGES = [
  { code: "ar", name: "Arabic" },
  { code: "zh-Hans", name: "Chinese Simplified" },
  { code: "zh-Hant", name: "Chinese Traditional" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "nl", name: "Dutch" },
  { code: "fi", name: "Finnish" },
  { code: "el", name: "Greek" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ms", name: "Malay" },
  { code: "nb", name: "Norwegian Bokmal" },
  { code: "pl", name: "Polish" },
  { code: "pt-BR", name: "Portuguese Brazil" },
  { code: "pt-PT", name: "Portuguese Portugal" },
  { code: "ru", name: "Russian" },
  { code: "sk", name: "Slovak" },
  { code: "sv", name: "Swedish" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" },
  { code: "vi", name: "Vietnamese" },
];

export const STATE_COLORS: Record<string, string> = {
  reviewed: "bg-blue-600",
  flagged: "bg-amber-600",
  translated: "bg-emerald-600",
  needs_review: "bg-yellow-600",
  not_translated: "bg-zinc-500",
  new: "bg-zinc-600",
  stale: "bg-zinc-600",
};

export const STATE_LABELS: Record<string, string> = {
  reviewed: "Reviewed",
  flagged: "Flagged",
  translated: "Translated",
  needs_review: "Needs Review",
  not_translated: "New",
  new: "New",
  stale: "Stale",
};
